---
- name: Update repository cache for debian/ubuntu
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install iperf3
  become: true
  ansible.builtin.package:
    name: "{{ iperf3_package }}"
    state: "{{ iperf3_package_state }}"
