---
- name: Update repository cache for debian/ubuntu
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
# when:
#   - ansible_pkg_mgr == "apt"

- name: Install iperf
  become: true
  ansible.builtin.package:
    name: "{{ iperf_package }}"
    state: "{{ iperf_package_state }}"
