---
- name: Deploy systemd iperf3@.service
  become: true
  ansible.builtin.template:
    src: 'templates/iperf3.service.j2'
    dest: '/etc/systemd/system/iperf3@.service'
    mode: 0644
    group: root
    owner: root
  register: result_service

- name: Deploy systemd iperf3
  become: true
  ansible.builtin.template:
    src: 'templates/iperf3.target.j2'
    dest: '/etc/systemd/system/iperf3.target'
    mode: 0644
    group: root
    owner: root
  register: result_target

- name: Reload systemd daemon and restart iperf3
  become: true
  ansible.builtin.systemd:
    name: iperf3.target
    state: restarted
    daemon_reload: true
  when: iperf3_systemd_enable | bool   # hier nog registers zodat als het resultaat veranderd is je de daemon reload


- name: Enable iperf3.target to start at system boot
  become: true
  ansible.builtin.systemd:
    name: 'iperf3@target'
    enabled: true
    masked: false
  when: iperf3_systemd_enable | bool   # hier nog registers zodat als het resultaat veranderd is je de daemon reload

- name: Masked systemd iperf3.target
  become: true
  ansible.builtin.systemd:
    name: 'iperf3.target'
    state: stopped
    enabled: false
    masked: true
  when: not iperf3_systemd_enable | bool

- name: Masked systemd iperf3@.service
  become: true
  ansible.builtin.systemd:
    name: 'iperf3@.service'
    state: stopped
    enabled: false
    masked: true
  when: not iperf3_systemd_enable | bool
