---
- name: Create group "{{ iperf3_system_group }}"
  become: true
  ansible.builtin.group:
    name: "{{ iperf3_system_group }}"
    system: true
    state: "present"

- name: Add the user "{{ iperf3_system_user }}"
  become: true
  ansible.builtin.user:
    name: "{{ iperf3_system_user }}"
    comment: "Iperf user"
    group: "{{ iperf3_system_group }}"
    shell: '/sbin/nologin'
    state: "present"
