---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * 2"

defaults:
  run:
    working-directory: 'tecleck.iperf3'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v3
        with:
          # needed for progressive mode to work
          fetch-depth: 0

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code.
        run: |
          set -e
          ansible-lint .
          yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2004

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'tecleck.iperf3'

      - name: Set up Python 3.
        uses: aactions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
